### ISSUE TITLE
It crashed on call showAtAnchorView().

### ISSUE THREAD

**Issue by dyguests** [zyyoona7/EasyPopup#14]
It call ` android.view.ContextThemeWrapper cannot be cast to android.app.Activity`.

My source:
![image](https://user-images.githubusercontent.com/7933189/38237383-ae8d1fd4-3759-11e8-9fe2-966e67b4515b.png)
```
        EasyPopup(textView.context)
                .setContentView<EasyPopup>(R.layout.popup_vehicle_picker)
                //是否允许点击PopupWindow之外的地方消失
                .setFocusAndOutsideEnable<EasyPopup>(true)
                //允许背景变暗
                .setBackgroundDimEnable<EasyPopup>(true)
                //变暗的透明度(0-1)，0为完全透明
                .setDimValue<EasyPopup>(0.4f)
                .createPopup<EasyPopup>()
                .showAtAnchorView(textView, VerticalGravity.BELOW, HorizontalGravity.CENTER, 0, 0)
```

Log:

```
04-03 16:01:14.574 32057-32057/? E/MtaSDK: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at com.zyyoona7.lib.EasyPopup.handleBackgroundDim(EasyPopup.java:607)
        at com.zyyoona7.lib.EasyPopup.showAtAnchorView(EasyPopup.java:452)
        at com.lxt.app.ui.maink6.helper.VehiclePickerHelper.popupVehiclePicker(VehiclePickerHelper.kt:35)
```
It happened at here:
![image](https://user-images.githubusercontent.com/7933189/38237436-cc98188a-3759-11e8-84dd-934c3562e4f7.png)

**Comment by dyguests** [comment]
fixed:

![image](https://user-images.githubusercontent.com/7933189/38238913-f1331830-375d-11e8-9465-7f0f0b71963c.png)
